apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    prometheus.io/rule: node_memory_active_bytes, node_cpu_seconds_total, up
    prometheus.io/alert: all
    github.com/project-slug: yarabora/backstage 
    grafana/overview-dashboard: 'http://localhost:3100/d/UDdpyzz7z/prometheus'
spec:
  type: service
  lifecycle: experimental
  owner: yarabora
