apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: whoami
  tags:
    - elastic-stack
    - data
    - kubernetes
    - aws
  description: |
    My name is Bora, living in Utrecht with my husband, working as a consultant at Capgemini.
  links:
    - title: My Github
      url: https://github.com/yarabora/backstage/blob/main/backstage-info.yaml
    - title: Instagram
      url: https://www.instagram.com/yara_bora/
    - title: Linkedin
      url: https://www.linkedin.com/in/bora-min-64639a230/

  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: person
  owner: Bora
  lifecycle: experimental
  providesApis: [example-grpc-api]
