apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    prometheus.io/rule: node_memory_active_bytes
    prometheus.io/alert: HighMemoryUsage
    github.com/project-slug: yarabora/backstage 
spec:
  type: service
  lifecycle: experimental
  owner: yarabora
